services:
  db:
    image: pgvector/pgvector:pg16
    container_name: raw_langchain_db
    environment:
      POSTGRES_DB: raw_langchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: raw_langchain_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - RELOAD=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/raw_langchain
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=raw_langchain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    restart: unless-stopped

volumes:
  postgres_data: 